---
- name: Install recommended packages (RedHat)
  yum:
    name: "{{ rh_packages }}"
  
- name: Update OS (RedHat)
  yum:
    name: '*'
    state: latest
  
- name: Check if reboot is needed (RedHat)
  shell: needs-restarting -r
  failed_when: None
  register: reboot_required
  changed_when: reboot_required.rc == 1
  notify:
    - reboot os
...
